version: '3.1'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ipdb
    ports:
      - 5432:5432